<?php require_once dirname(__FILE__).'/empluser-list.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-unitgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-unitform.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-deptgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-deptform.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-sitegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/empluser-siteform.phtml' ?>



<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Post By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-postby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Post Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-postdate"></span>
		</div>
	</div>	
</div>