<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Employee User</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_empl_id" class="easyui-textbox" mapping="empl_id" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">NIK</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_empl_nik" class="easyui-textbox" mapping="empl_nik" uppercase="true" maxlength="30" style="width: 400px" data-options="multiline: false , readonly: true, disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_empl_name" class="easyui-textbox" mapping="empl_name" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false , readonly: true, disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_dept_name" class="easyui-textbox" mapping="dept_name" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false , readonly: true, disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Site Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_site_name" class="easyui-textbox" mapping="site_name" uppercase="true" maxlength="90" style="width: 400px" data-options="multiline: false , readonly: true, disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_empluser_allowviewalldept" class="easyui-checkbox c1" mapping="empluser_allowviewalldept" data-options="label: 'Allow View All Dept', labelPosition: 'after', checked: false, labelWidth:'200px' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_empluser_allowviewallunit" class="easyui-checkbox c1" mapping="empluser_allowviewallunit" data-options="label: 'Allow View All Unit', labelPosition: 'after', checked: false, labelWidth:'200px' ">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_empluser_allowviewallsite" class="easyui-checkbox c1" mapping="empluser_allowviewallsite" data-options="label: 'Allow View All Site', labelPosition: 'after', checked: false, labelWidth:'200px' ">
			</div>
		</div>				

		<div class="form_row">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_user_id" class="easyui-combo" style="width: 400px" mapping="user_id" display="user_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'User harus diisi', prompt: '-- PILIH --'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editdeptgrid')">Owned Dept</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editunitgrid')">Owned Unit</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 0px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editsitegrid')">Owned Site</div>
			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

