<div id="pnl_edithrcdtfamform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Family</div>
		<a id="pnl_edithrcdtfamform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edithrcdtfamform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_edithrcdtfamform-form">

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-txt_hrcdtfam_id" class="easyui-textbox" mapping="hrcdtfam_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Relation</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-cbo_hrrel_id" class="easyui-combo" style="width: 400px" mapping="hrrel_id" display="hrrel_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Relation harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_edithrcdtfamform-cbo_hrrel_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>
		<?php $cp=__DIR__ . '/candidate-candidatefamform-relationship.phtml'; if (is_file($cp)) { include $cp; } ?>

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-txt_hrcdtfam_name" class="easyui-textbox" mapping="hrcdtfam_name" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Gender</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-cbo_gender_id" class="easyui-combo" style="width: 400px" mapping="gender_id" display="gender_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Gender harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_edithrcdtfamform-cbo_gender_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Birth Place</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-txt_hrcdtfam_birthplace" class="easyui-textbox" mapping="hrcdtfam_birthplace" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Birth Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-dt_hrcdtfam_birthdate" class="easyui-datebox" style="width: 400px" mapping="hrcdtfam_birthdate" data-options="editable:false , required: false">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtfamform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Handphone</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-txt_hrcdtfam_handphone" class="easyui-textbox" mapping="hrcdtfam_handphone"  maxlength="14"  style="width: 400px" data-options="multiline:false , required: false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtfamform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">hrcdt ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtfamform-txt_hrcdt_id" class="easyui-textbox" mapping="hrcdt_id"  maxlength="36"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edithrcdtfamform-autoadd" type="checkbox"><label for="pnl_edithrcdtfamform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edithrcdtfamform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_edithrcdtfamform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_edithrcdtfamform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_edithrcdtfamform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_edithrcdtfamform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
