<div id="pnl_edithrcdtfamgrid">
	<div class="fgta-page-title">Daftar Family</div>
	<div id="pnl_edithrcdtfamgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edithrcdtfamgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edithrcdtfamgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edithrcdtfamgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->


	<?php
	$customheadpanel = __DIR__.'/candidate-hrcdtfamgrid-customheadpanel.phtml';
	if (is_file($customheadpanel)) {
		include $customheadpanel;
	} 
	?>

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edithrcdtfamgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/candidate-hrcdtfamgrid-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>
			<thead>

				<tr>
<th type="check">chk</th>					
					<th mapping="hrrel_name">hrrel_name</th>
					<th mapping="hrcdtfam_name">hrcdtfam_name</th>
					<th mapping="gender_name">gender_name</th>
					<th mapping="hrcdtfam_birthplace">hrcdtfam_birthplace</th>
					<th mapping="hrcdtfam_birthdate">hrcdtfam_birthdate</th>
					<th mapping="hrcdtfam_handphone">hrcdtfam_handphone</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Relation</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Gender</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Birth Place</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Birth Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Handphone</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
			<?php } ?>
		</table>
	</div>



	<div class="pnl_edithrcdtfamgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edithrcdtfamgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edithrcdtfamgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>



	<?php
	$customfootpanel = __DIR__.'/candidate-hrcdtfamgrid-customfootpanel.phtml';
	if (is_file($customfootpanel)) {
		include $customfootpanel;
	} 
	?>

</div>	
