<div id="pnl_edithrcdtjobexpgrid">
	<div class="fgta-page-title">Daftar Job Experience</div>
	<div id="pnl_edithrcdtjobexpgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edithrcdtjobexpgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edithrcdtjobexpgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edithrcdtjobexpgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->


	<?php
	$customheadpanel = __DIR__.'/candidate-hrcdtjobexpgrid-customheadpanel.phtml';
	if (is_file($customheadpanel)) {
		include $customheadpanel;
	} 
	?>

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edithrcdtjobexpgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/candidate-hrcdtjobexpgrid-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>
			<thead>

				<tr>
<th type="check">chk</th>					
					<th mapping="hrcdtjobexp_company">hrcdtjobexp_company</th>
					<th mapping="hrcdtjobexp_position">hrcdtjobexp_position</th>
					<th mapping="hrcdtjobexp_dtjoin">hrcdtjobexp_dtjoin</th>
					<th mapping="hrcdtjobexp_dtleave">hrcdtjobexp_dtleave</th>
					<th mapping="hrcdtjobexp_jobdescr">hrcdtjobexp_jobdescr</th>
					<th mapping="hrcdtjobexp_reasonleave">hrcdtjobexp_reasonleave</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Company</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Position</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date Join</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date Leave</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Job Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Reason Leave</td>

					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
			<?php } ?>
		</table>
	</div>



	<div class="pnl_edithrcdtjobexpgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edithrcdtjobexpgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edithrcdtjobexpgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>



	<?php
	$customfootpanel = __DIR__.'/candidate-hrcdtjobexpgrid-customfootpanel.phtml';
	if (is_file($customfootpanel)) {
		include $customfootpanel;
	} 
	?>

</div>	
