<div id="pnl_edithrcdtjobexpform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Job Experience</div>
		<a id="pnl_edithrcdtjobexpform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edithrcdtjobexpform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_edithrcdtjobexpform-form">

		<div class="form_row pnl_edithrcdtjobexpform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-txt_hrcdtjobexp_id" class="easyui-textbox" mapping="hrcdtjobexp_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtjobexpform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Company</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-txt_hrcdtjobexp_company" class="easyui-textbox" mapping="hrcdtjobexp_company" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtjobexpform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Position</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-txt_hrcdtjobexp_position" class="easyui-textbox" mapping="hrcdtjobexp_position" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Position harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtjobexpform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date Join</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-dt_hrcdtjobexp_dtjoin" class="easyui-datebox" style="width: 400px" mapping="hrcdtjobexp_dtjoin" data-options="editable:false , required: true, invalidMessage: 'Date Join harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtjobexpform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Date Leave</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-dt_hrcdtjobexp_dtleave" class="easyui-datebox" style="width: 400px" mapping="hrcdtjobexp_dtleave" data-options="editable:false , required: true, invalidMessage: 'Date Leave harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtjobexpform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Job Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-txt_hrcdtjobexp_jobdescr" class="easyui-textbox" mapping="hrcdtjobexp_jobdescr"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>
		
					<div class="form_row pnl_edithrcdtjobexpform_row" >
						<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Job Descr</div>
						<div class="form_input_col" style="border: 0px solid black">
							<input id="pnl_edithrcdtjobexpform-editor" class="easyui-texteditor" style="width:400px;height:300px;padding:20px">
						</div>
					</div>					
					

		<div class="form_row pnl_edithrcdtjobexpform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reason Leave</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-txt_hrcdtjobexp_reasonleave" class="easyui-textbox" mapping="hrcdtjobexp_reasonleave"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, multiline: true, invalidMessage: 'Reason Leave harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtjobexpform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">hrcdt ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtjobexpform-txt_hrcdt_id" class="easyui-textbox" mapping="hrcdt_id"  maxlength="36"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edithrcdtjobexpform-autoadd" type="checkbox"><label for="pnl_edithrcdtjobexpform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edithrcdtjobexpform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_edithrcdtjobexpform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_edithrcdtjobexpform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_edithrcdtjobexpform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_edithrcdtjobexpform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
