<div id="pnl_edithrcdtorgform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Organization</div>
		<a id="pnl_edithrcdtorgform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edithrcdtorgform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_edithrcdtorgform-form">

		<div class="form_row pnl_edithrcdtorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtorgform-txt_hrcdtorg_id" class="easyui-textbox" mapping="hrcdtorg_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtorgform-txt_hrcdtorg_name" class="easyui-textbox" mapping="hrcdtorg_name" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtorgform-txt_hrcdtorg_city" class="easyui-textbox" mapping="hrcdtorg_city"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'City harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Position</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtorgform-txt_hrcdtorg_position" class="easyui-textbox" mapping="hrcdtorg_position" uppercase="true" maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Position harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtorgform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtorgform-txt_hrcdtorg_descr" class="easyui-textbox" mapping="hrcdtorg_descr"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: false, multiline: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdtorgform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">hrcdt ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdtorgform-txt_hrcdt_id" class="easyui-textbox" mapping="hrcdt_id"  maxlength="36"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edithrcdtorgform-autoadd" type="checkbox"><label for="pnl_edithrcdtorgform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edithrcdtorgform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_edithrcdtorgform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_edithrcdtorgform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_edithrcdtorgform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_edithrcdtorgform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
