<div id="pnl_edithrcdteduform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Education</div>
		<a id="pnl_edithrcdteduform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_edithrcdteduform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_edithrcdteduform-form">

		<div class="form_row pnl_edithrcdteduform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-txt_hrcdtedu_id" class="easyui-textbox" mapping="hrcdtedu_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdteduform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Level</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-cbo_edu_id" class="easyui-combo" style="width: 400px" mapping="edu_id" display="edu_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Level harus diisi'"  validType="requiredcombo['pnl_edithrcdteduform-cbo_edu_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdteduform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-txt_hrcdtedu_name" class="easyui-textbox" mapping="hrcdtedu_name"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdteduform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Title</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-txt_hrcdtedu_title" class="easyui-textbox" mapping="hrcdtedu_title"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: false ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdteduform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">City</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-txt_hrcdtedu_city" class="easyui-textbox" mapping="hrcdtedu_city"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'City harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdteduform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">GPA</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-txt_hrcdtedu_gpa" class="easyui-numberbox" mapping="hrcdtedu_gpa" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, invalidMessage: 'GPA harus diisi'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edithrcdteduform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">hrcdt ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edithrcdteduform-txt_hrcdt_id" class="easyui-textbox" mapping="hrcdt_id"  maxlength="36"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_edithrcdteduform-autoadd" type="checkbox"><label for="pnl_edithrcdteduform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_edithrcdteduform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_edithrcdteduform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_edithrcdteduform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_edithrcdteduform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_edithrcdteduform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
