DROP TABLE tmp_greatdaysum;
CREATE TABLE tmp_greatdaysum(
	id varchar(14) PRIMARY KEY,
	dt date,
	nama varchar(90),
	nik varchar(20),
	empl_id varchar(30),
	position varchar(60),
	unit varchar(60),
	shift varchar(30),
	schd_in time,
    schd_out time,
    act_in time, 
    act_invar int not null default 0,
    act_out time, 
    act_outvar int not null default 0,
    break_start time, 
    break_end time, 
    daytype varchar(30),
    eff_work int not null default 0,
    overtime int not null default 0,
    overtime_index varchar(30),
    overtime_meal int not null default 0,
    overtime_transport int not null default 0,
    statusatt varchar(30),
    statusother varchar(30),
    remark varchar(255),
	score_late int not null default 0,
	score_workeff int not null default 0,
	score_add int not null default 0,
	score_total decimal(3,2)
) ENGINE=MEMORY;